prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan

- README.md
> [진욱] 이슈 자동 닫힘 테스트

- .prettierrc
- package-lock.json
- src/components/atoms/Flex.tsx
- src/components/atoms/Image.tsx
- src/stories/components/atoms/Flex.stories.tsx
- src/stories/components/atoms/Image.stories.tsx
close #3 
Flex 컴포넌트 구현
Image 컴포넌트 구현
prettier 설정 변경
jsxBracketSameLine 속성이 deprecated 됨에 따라 bracketSameLine 으로 변경하였습니다.
> [진욱] Atom 컴포넌트 구현

- src/components/atoms/Button.tsx
- src/components/atoms/Input.tsx
> [김동현] css 속성 오타 수정

- src/constants/theme.ts
close #16 
- 테마 : 라이트모드 색상 상수화 완료
- 테마 : 닼크모드 색상 상수화 완료
- 라이트 모드에서 다크 모드 색상으로 변경할때 헷갈리면 라이트 모드 기준으로 같은 이름을 가진 key값으로 변경
> feat: theme color 상수화 완료

- src/main.tsx
- src/styles/globalStyles.ts
> [ 혜수 ] global css setting font & reset 설정

- src/components/atoms/Button.tsx
- src/components/atoms/Input.tsx
- src/stories/components/atoms/Button.stories.tsx
- src/stories/components/atoms/Input.stories.tsx
close #27 
- Button, Input onClick, onChange처리, 
- 기본값 props 타입 옵셔널 정의
- Input 컴포넌트 placeholder 속성 추가
> [ 김동현 ] Button, Input onClick, onChange처리, 기본값 props 타입 옵셔널 정의

- src/components/atoms/Button.tsx
- src/components/atoms/Input.tsx
- src/stories/components/atoms/Button.stories.tsx
close #42 
- onClick, onChange 타입 속성 삭제
혹시나, 또 빼먹은 부분이 있으면 바로 멘션해주세요!
> fix: onClick, onChange 타입 속성 삭제

- src/App.tsx
- src/components/templates/PageTemplate/PageTemplate.styles.ts
- src/components/templates/PageTemplate/PageTemplate.tsx
- src/components/templates/PageTemplate/index.ts
- src/main.tsx
- src/router/index.tsx
- src/styles/globalStyles.ts
close #35 
- 글로벌 스타일 resetcss 적용
- 글로벌 스타일에 폰트컬러, 배경컬러, 테두리컬러 적용
- PageTemplate 구현 및 라우터에 적용
- 로그인, 회원가입, 비밀번호 변경 페이지는 템플릿을 사용하지 않습니다.
- 추후 별도 템플릿 구현할 수 있음
- border-color는 `var(--border-color)` 처럼 변수로 사용하시면 됩니다.
> [ 진욱 ] PageTemplate 제작

- src/apis/comment/createComment.ts
- src/apis/user/authUser.ts
- src/components/molecules/CommentForm.tsx
- src/stories/components/molecules/CommentForm.stories.tsx
- src/types/apis/users/AuthUser.ts
close #51 
- CommentForm 제작
- authUser API 함수 제작 및 타입 정의
- createComment API 함수 제작
> [ 김동현 ] 댓글 폼 molecule 만들기 

- src/App.tsx
- src/components/Login.tsx
- src/stores/myInfo.store.ts
close #60 
- myInfo.store 구현
- Login 컴포넌트 구현
Login 컴포넌트는 어디에 둬야할지 몰라 components 폴더 최상단에 배치해 두었습니다.
파일 위치가 마음에 안 든다면 얘기해 주세요!
> [ 진욱 ] myInfoStore 구현 및 Login 컴포넌트 구현

- src/components/organisms/Sidebar/ThemeToggle.tsx
- src/components/organisms/Sidebar/index.tsx
close #65 
- 사이드바 로그아웃 버튼 디자인을 변경했습니다.
- Figma
> [ 혜수 ] 사이드바 로그아웃 버튼 디자인 변경

- src/components/organisms/Sidebar/ThemeToggle.tsx
> [ 혜수 ] 다크모드 토글버튼 패딩 제거

- src/components/organisms/Sidebar/ThemeToggle.tsx
- src/constants/index.ts
- src/router/index.tsx
close #62 
- #62 
- /create 라우트 추가 완료
- 현재 padding 제거 PR이 merge 되지 않아 커밋이 중복되었는데 먼저 제출한 PR이 머지되면 수정하겠습니다!
> [ 혜수 ] 새 글 작성 라우트 추가 /create

- src/components/organisms/ArticleWrite/ArticleTag.tsx
- src/components/organisms/ArticleWrite/ChannelSelect.tsx
- src/components/organisms/ArticleWrite/index.tsx
close #75 
- 태그 엔터 입력시 컴포넌트로 추가 완료
- tag type string -> string[]으로 변경
- 글 생성시 채널 선택 서버에서 채널 받아와 적용 완료
- 글 작성 완료시 서버로 전송해 글 생성 완료
- ChannelSelect 디자인 변경 완료
- title isQuestion은 진욱님 머지 완료시 수정 예정
> [ 혜수 ] 글 작성 페이지 API 연결 완료

- src/apis/notification/createNotification.ts
- src/apis/notification/getNotifications.ts
- src/apis/notification/readNotifications.ts
- src/components/atoms/Dropdown.tsx
- src/components/organisms/ArticleHeader/ArticleHeader.tsx
- src/components/organisms/NotiDropdown/NotiDropdown.styles.ts
- src/components/organisms/NotiDropdown/NotiDropdown.tsx
- src/components/organisms/NotiDropdown/index.ts
- src/hooks/api/useNotificationCreateMutation.ts
- src/hooks/api/useNotificationsQuery.ts
- src/hooks/api/useNotificationsReadMutation.ts
- src/types/apis/notifications/CreateNotification.ts
- src/types/apis/notifications/GetNotifications.ts
- src/types/models/Notification.ts
- src/types/models/User.ts
close #86 
- [알림 관련 모델 타입들 수정](https://github.com/prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan/commit/29e03487516770ac683f67229e91ca2f83d389b0)
- [알림 관련 api 함수 작성](https://github.com/prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan/commit/a7d70dac9ba70a3dc4056f4978c22809a511a371)
- [알림 관련 query, mutation 훅 작성](https://github.com/prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan/commit/c87cb3187e5f1a5ec5423a1e02e3f61f954138e8)
- [좋아요 시 알림 생성 기능 추가](https://github.com/prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan/commit/e12f15c3a07de850a9db046859e566b209acc795)
- [Dropdown 컴포넌트 작성](https://github.com/prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan/commit/816f4ca2362f898c1e434443baffab17899b251d)
- [알림 드롭다운 컴포넌트 작성](https://github.com/prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan/commit/c3c85cc15c9284bc346b4214d92e1ff977c48a5a)
드롭다운 컴포넌트는 …
> [ 진욱 ] 알림 드롭다운 구현

- package-lock.json
- package.json
- src/App.tsx
- src/components/Toaster.tsx
close #79 
- react hot toast 라이브러리 설치
- Toaster 기본 옵션 지정
- 토스터에 테마도 적용해 두었습니다.
> [ 진욱 ] react hot toast 의존성 추가

- src/components/atoms/Icon.tsx
- src/components/atoms/Text.tsx
- src/components/molecules/IconText.tsx
- src/components/organisms/Sidebar/Sidebar.styles.ts
- src/components/organisms/Sidebar/index.tsx
close #73 
- #73 
- 세로 반응형만 추가
- ~~cd3eab1 참고하시고 만약 src/components/atoms/Text.tsx에 아래의 코드를 추가했을 때 문제가 생긴다면 머지하지 마시고 알려주세요!~~
```
overflow: hidden;
text-overflow: ellipsis;
white-space: nowrap;
```
- d5ce002 방식으로 수정했습니다. 이 부분은 props로 전달을 어떤 방식으로 해야하는지 고민을 했는데 마땅한 방법이 안떠오르네요.
IconText를 사용할 때 두 줄이상 넘어가는 text를 사용할 일이 있을까요?
> [ 혜수 ] 사이드바 채널 생성시 채널 동적으로 변경 되도록 수정, 디자인 수정

- src/components/organisms/Card/CardFooter.styles.ts
close #99 
- [design: Card 컴포넌트 높이 일정하게 수정](https://github.com/prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan/commit/10a064f02da24d7c77d7cc183311c6566a033022)
> [ 진욱 ] CardFooter 고정 높이로 수정

- src/components/organisms/Sidebar/Sidebar.styles.ts
- src/components/organisms/Sidebar/index.tsx
> [ 혜수 ] 사이드바 로그인 여부에 따라 다르게 보이게 수정

- src/pages/UserPage/ArticleList.tsx
- src/pages/UserPage/UserInfo.tsx
close #100 
- 로그인 하지 않은 사용자 혹은 본인이 아닌 사용자가 특정 사용자의 정보를 변경할 수 있는 버튼이 보이는 문제
- 인증이 필요하지 않은 API 함수가 인증이 필요하도록 설정되어있음.
- map 순회 컴포넌트 key가 안붙어 있음.
> [ 동현 ] 유저페이지 수정

- src/components/organisms/ArticleWrite/index.tsx
> [ 혜수 ] 글 작성시 채널과 제목 입력이 되어있지 않을 때 toast 추가

- src/components/organisms/Sidebar/index.tsx
close #109 
- 사이드바 내 정보 클릭시 자신의 정보 페이지로 이동 추가
> [ 혜수 ] 사이드바 내 정보 클릭시 자신의 정보 페이지로 이동 추가

- src/apis/user/updatePassword.ts
- src/components/atoms/Button.tsx
- src/hooks/api/useUserPasswordUpdateMutation.ts
- src/pages/PasswordPage/PasswordPage.tsx
- src/router/index.tsx
close #91
router에 PasswordPage 컴포넌트 대입
updatePassword 제작
useUserPasswordUpdateMutation 제작
PasswordPage, 비밀번호 변경 기능 제작
PasswordPage, 비밀번호 확인 기능 제작
UserForm molecule 컴포넌트를 수정해야 할 것 같습니다.
> [ 동현 ] 비밀번호 변경 페이지 

- src/components/molecules/CommentForm.tsx
close #112
댓글 폼 버튼 텍스트 변경(reply => 댓글 쓰기)
> [ 동현 ] 댓글 폼 컴포넌트, 버튼 textContent 수정 

- src/components/molecules/CommentForm.tsx
- src/components/organisms/Article/Article.tsx
close #124 
- ArticleEditor 댓글 폼에 삽입
- ArticlePage에서 isLogged인으로 숨기기 구현
- 에디터로 편집 후 제출 할 시, 에디터가 초기화 되어야 하는 이슈는 혜수님이 처리하시기로 하셨습니다.
> [ 동현 ] 댓글 폼 컴포넌트 에디터 교체, 비로그인 시 댓글 폼 숨김

- src/components/organisms/Thread/Thread.styles.ts
- src/components/organisms/Thread/Thread.tsx
close #127
쓰레드에서 UserInfo 클릭 시 유저 페이지 이동 기능
> [ 동현 ] 쓰레드에서 UserInfo 클릭 시 유저 페이지 이동 기능

- src/pages/UserPage/ArticleList.tsx
- src/pages/UserPage/ChannelTab.tsx
- src/pages/UserPage/UserInfo.tsx
close #130
- loggedInUser의 id값과 현재 id값이 같지 않다면, Image를 클릭할 수 없게 만들기
- 전체글을 보여줄 수 있는 탭을 만들기
> [ 동현 ] 본인 아닐 시 유저정보 이미지 변경 불가, 전체글 보여주기 탭

- src/components/molecules/ConfirmModal.tsx
- src/components/organisms/ArticleHeader/ArticleHeader.tsx
- src/components/organisms/Thread/Thread.tsx
close #134
- confirm 모달 만들기
- handleDeleteButtonClick 시 모달 띄우는 기능 추가
- handleDeleteComment 만들어 모달 띄우는 기능 추가
> [ 동현 ] 글 삭제, 댓글 삭제 시 모달 띄우기 

- src/pages/LoginPage.tsx
- src/pages/PasswordPage.tsx
- src/pages/SignUpPage.tsx
- src/utils/withEnter.ts
close #140 
- withEnter 유틸함수 만들기
- 각 핸들러에 withEnter 적용하기
> [ 동현 ] 로그인, 회원가입, 패스워드 페이지 엔터키 제출 기능

- src/components/organisms/Sidebar/SidebarChannels.tsx
close #144 
- 채널 한글화 작업
- 한글로 만든 채널 이름 확인 부탁드립니다.
> [ 혜수 ] 채널 한글화 작업

- src/pages/SignUpPage.tsx
close #142 
* 비밀번호 인풋 만들기
* 비밀번호 확인 검증 조건문 만들기
> [ 동현 ] 회원가입시, 비밀번호 확인 만들기

- src/components/organisms/Card/Card.styles.ts
- src/components/organisms/Card/Card.tsx
- src/components/organisms/Card/CardSkeleton.tsx
- src/components/organisms/CardList/CardList.styles.ts
- src/components/organisms/CardList/CardList.tsx
- src/components/organisms/CardList/index.ts
- src/constants/media.ts
- src/pages/ChannelPage/ChannelPage.styles.ts
- src/pages/ChannelPage/ChannelPage.tsx
- src/pages/ChannelPage/ChannelPageSkeleton.tsx
- src/pages/UserPage/ArticleList.tsx
- src/stories/components/organisms/Card.stories.tsx
close #152 
- [feat: CardList 컴포넌트 분리](https://github.com/prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan/commit/840982082249613140f0b75d9c5dfc7f944ebd9d)
- [refactor: 채널 페이지에 CardList 컴포넌트 추가](https://github.com/prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan/commit/bd454859a9ad58131745fde8da0626e40772f2d3)
- [refactor: 유저 페이지에서 CardList 컴포넌트 사용하게 변경](https://github.com/prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan/commit/766856619e4fd1bab6f9752be7bb5a11f55d7c63)
카드 컴포넌트를 변경하니 UserPage 파일에서 오류가 나서 커밋이 안되더라구요.
커밋을 위해  조금 수정해두었습니다.
너비값 피드백 받습니다.
개선할 점 피드백 받습니다.
> [ 진욱 ] 카드 리스트 그리드로 변경 및 반응형 작업

- src/components/organisms/Card/CardFooter.tsx
- src/components/organisms/NotiDropdown/NotiDropdown.tsx
- src/components/organisms/Thread/Thread.tsx
- src/utils/createdAtToString.ts
close #156 
- [feat: createdAtToString 유틸 함수 작성](https://github.com/prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan/commit/12bc6af1ad12fa041d1e0c3bf1320298fdef7a2d)
> [ 진욱 ] 작성시간 보여주기 변경

- src/components/molecules/CommentForm.tsx
- src/components/organisms/Article/Article.tsx
- src/components/organisms/NotiDropdown/NotiDropdown.styles.ts
- src/components/organisms/NotiDropdown/NotiDropdown.tsx
- src/components/organisms/NotiDropdown/filterNotifications.ts
- src/stories/components/molecules/CommentForm.stories.tsx
close #150 
- [feat: 댓글 작성 시 알림 생성기능 추가](https://github.com/prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan/pull/164/commits/9a66da61f8f57734d560713492706f4db953faaf)
- [feat: 알림 필터링 기능 추가](https://github.com/prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan/pull/164/commits/258d6cf932a36f52298e4eac0ce595cc188f6b67)
- [design: 알림 드롭다운 높이 계산 css 추가](https://github.com/prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan/pull/164/commits/39636c271fa4df4ae85cdd5425a89e1162057f8f)
> [ 진욱 ] 댓글 시 알림 생성, 알림 중복 제거

- src/apis/article/getArticles.ts
- src/assets/svg/index.ts
- src/assets/svg/next.svg
- src/assets/svg/prev.svg
- src/components/organisms/ArticlesByChannelSlider/ArticlesByChannelSlider.style.ts
- src/components/organisms/ArticlesByChannelSlider/ArticlesByChannelSlider.tsx
- src/components/organisms/ArticlesByChannelSlider/CardSlider.tsx
- src/components/organisms/ArticlesByChannelSlider/index.ts
- src/hooks/api/useArticlesQuery.ts
- src/pages/HomePage.tsx
- src/router/index.tsx
close #163
- ArticlesQuery (글 전체 목록 가져오는 쿼리), getArticles(글 전체 목록 가져오는 API 함수) 제작
- prev, next svg 추가
- 채널별 글 목록 기능
- 뷰포트 별 페이지네이션 기능
- 최신순, 인기순 정렬 기능
> [ 동현 ] 채널 별 글 가져오는 슬라이더 컴포넌트 , 홈페이지 제작

- src/components/atoms/Dropdown.tsx
- src/components/atoms/Modal.tsx
- src/components/organisms/Card/Card.styles.ts
- src/styles/globalStyles.ts
close #155 
- [feat: 페이드인 키프레임 추가](https://github.com/prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan/commit/40804977e9502d700551a39262b900e9e4e445e2)
- [feat: 모달, 드롭다운에 페이드인 애니메이션 추가](https://github.com/prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan/commit/4e89d2cf6833d359ddfd09cb5c74bea739e50eda)
- [feat: 카드에 호버 트랜지션 추가](https://github.com/prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan/commit/d2f79c71d011dd3b7190728a00bd9a0030ff6ae1)
> [ 진욱 ] 트랜지션 - 카드, 알림, 모달

- src/components/organisms/NotiDropdown/NotiDropdown.styles.ts
- src/components/organisms/NotiDropdown/NotiDropdown.tsx
close #170 
- [feat: 알림 없을 때 알림 없음 표시 기능 추가](https://github.com/prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan/commit/2e6b61cfc2caf56dd0476c6ed18a76fc001c9a50)
> [ 진욱 ] 알림 없을 때 알림 없음 표시

- src/components/organisms/SearchModal/SearchModal.styles.ts
- src/components/organisms/SearchModal/SearchModal.tsx
close #173 
[feat: 검색 모달 툴팁 기능 추가](https://github.com/prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan/commit/262acd0cbda2a1a83b0d47a99f5f03e25a3ece1b)
> [ 진욱 ] 검색 모달에 현재 선택된 검색옵션 알려주기

- src/apis/channel/getChannels.ts
- src/components/organisms/CardList/CardList.styles.ts
- src/components/organisms/Sidebar/SidebarChannels.tsx
- src/constants/channel.ts
- src/hooks/api/useArticleDeleteMutation.ts
- src/pages/ChannelPage/ChannelPage.tsx
- src/pages/SearchPage/SearchPage.tsx
- src/pages/UserPage/ArticleList.tsx
- src/pages/UserPage/ChannelTab.tsx
- src/pages/UserPage/UserInfo.tsx
- src/pages/UserPage/UserPage.style.ts
- src/pages/UserPage/UserPage.tsx
- src/styles/globalStyles.ts
close #154 #132 
- [feat: 채널명 한글화](https://github.com/prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan/commit/a11daeb51a1024945b2f1021eb33fbf3925a73c0)
- [design: 스크롤바 스타일 추가](https://github.com/prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan/commit/700044f1753135b70fcf566dcec1b5865cbfb6fb)
- [design: 유저페이지 스타일 수정](https://github.com/prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan/commit/383247c3db0e4b34f358e7871a3e0d977d958ac7)
> [ 진욱 ] 스크롤바 스타일링, 유저페이지 스타일 변경, 채널명 한글화

- src/components/templates/PageTemplate/PageTemplate.tsx
- src/stores/resize.store.ts
close #182 
- zustand를 이용해 전역 store 추가 -> width 값 저장
- resize시 과도한 연산 방지를 위해 timer 추가
> [ 혜수 ] resize store 추가

- src/components/molecules/CommentForm.tsx
- src/components/organisms/ArticleWrite/ArticleEdit.tsx
- src/components/organisms/ArticleWrite/ArticleWrite.tsx
- src/styles/globalStyles.ts
close #184 
- [fix: 에디터의 전체화면 버튼 없애기](https://github.com/prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan/commit/512c40a617d95be59ab352c4640d9816e34811b1)
> [ 진욱 ] 에디터 전체화면 버튼 없애기

- src/components/atoms/Dropdown.tsx
- src/components/organisms/NotiDropdown/NotiDropdown.styles.ts
- src/components/organisms/NotiDropdown/NotiDropdown.tsx
- src/components/organisms/Sidebar/SidebarMain.tsx
close #200 
- [refactor: 드롭다운 컴포넌트 리액트 포탈 사용하게 변경](https://github.com/prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan/commit/f0a75cb07b9efa5a8bf557257e27d266417880c7)
- [refactor: 드롭다운 변경점 반영](https://github.com/prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan/commit/b31d8c963656c6093cc878433c7805d6be906e29)
- [feat: 알림드롭다운의 위치를 잡아주기 위한 로직 추가](https://github.com/prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan/commit/03238a5fb6e8ccd61ffeeb2fb084bc72d24962f6)
> [ 진욱 ] 드롭다운 컴포넌트 리액트 포탈로 변경

- src/components/molecules/FallbackPage.tsx
- src/components/molecules/Spinning.tsx
- src/components/organisms/Article/ArticleSkeleton.tsx
- src/components/organisms/Article/index.ts
- src/router/index.tsx
close #205 
- [feat: FallbackPage 컴포넌트 작성](https://github.com/prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan/commit/5bf03d99f56e6b7fc9a949e1dd24671e89332edf) 
- [feat: Spinning 컴포넌트가 너비값을 받을 수 있게 변경](https://github.com/prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan/commit/8720961ef6b530c9bc6a41303fde85fcc644aea1)
- [feat: 검색, 유저 페이지 로딩처리](https://github.com/prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan/commit/26626aa79e4820a03e009645f11df8e8a60f1bca)
> [ 진욱 ] 검색, 유저페이지 로딩처리

- src/pages/UserPage/ChannelTab.styles.ts
- src/pages/UserPage/ChannelTab.tsx
close #208 
- [feat: 유저페이지 채널 탭 탐색버튼 추가](https://github.com/prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan/commit/0be40ca43d2386f7a190c7b1b1ed9343b880f13f)
> [ 진욱 ] 유저페이지 채널탭에 탐색 버튼 추가

- src/components/molecules/EmptyAlert/EmptyAlert.styles.ts
- src/components/organisms/Article/Article.styles.ts
- src/components/organisms/ArticleHeader/ArticleHeader.tsx
- src/components/organisms/ArticleWrite/ArticleEdit.tsx
- src/components/organisms/ArticleWrite/ArticleWrite.styles.ts
- src/components/organisms/ArticleWrite/ArticleWrite.tsx
- src/components/organisms/NotiDropdown/NotiDropdown.tsx
- src/types/models/Notification.ts
close #188 
- [fix: 편집기 작성버튼 위치 수정](https://github.com/prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan/commit/c32aa3a6b3b2239c27ab66a2fa156b5cba425c87)
- [fix: 알림 안가던 것 수정](https://github.com/prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan/pull/213/commits/d7b6542c16e1be8b6e090c65394021c22ccd2eda)
> [ 진욱 ] 편집기 작성버튼 위치 수정, 좋아요 알림 안가던 것 수정

- src/hooks/api/useUserProfileUploadMutation.ts
- src/hooks/api/useUserUpdateMutation.ts
- src/pages/UserPage/UserPage.tsx
close #190 
- 변경 성공시, toast UI 표시
- 변경 실패시, toast UI 표시
- 닉네임 변경 검증 코드 추가
> [ 동현 ]  유저 정보 변경 기능 개선

- src/constants/regex.ts
- src/pages/LoginPage.tsx
- src/pages/PasswordPage.tsx
- src/pages/SignUpPage.tsx
close #196 
- 각 submit 핸들러에 toast UI를 적용한다.
- 정규식 패턴에 숫자를 포함할 수 있게 한다.
> [ 동현 ] 회원가입, 로그인, 패스워드 변경 성공 시 toast UI 띄우기, 닉네임 정규식 패턴 수정

- src/components/molecules/ConfirmModal.tsx
- src/components/organisms/Sidebar/SidebarFooter.tsx
close #189 
- #189
- 모달 버튼 색상도 변경 했습니다.
> [ 혜수 ] 로그아웃시 모달로 확인하기

- src/pages/UserPage/ChannelTab.tsx
- src/pages/UserPage/UserInfo.tsx
- src/pages/UserPage/UserPage.tsx
close #217 
- [fix: 유저페이지 너비값 조정](https://github.com/prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan/commit/8a879191d3a2cce8c9ab44413efc5dc915b92e69)
- [feat: resize 이벤트 핸들러 추가](https://github.com/prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan/commit/90e4b12f3e147fc0bc6d4b7caa158127c5e658f2)
> [ 진욱 ] 유저페이지 반응형 수정

- src/components/organisms/FloatingButtons/FloatingButtons.tsx
close #219 
- [fix: 게시글페이지일 떄 플로팅 버튼 위치값 조정](https://github.com/prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan/commit/801170bff214965d1e1e5384bdf2d528aa579ba3)
> [ 진욱 ] 게시글 페이지에서 글 작성 버튼 위치 조정

- src/hooks/api/useLoginMutation.ts
- src/hooks/api/useSignUpMutation.ts
- src/hooks/api/useUserPasswordUpdateMutation.ts
- src/main.tsx
- src/pages/LoginPage.tsx
- src/pages/PasswordPage.tsx
- src/pages/SignUpPage.tsx
close #222
- useLoginMutation 제작 및 교체
- useSignUpMutation 제작 및 교체
- useUserPasswordUpdate 수정
- mutation 전역설정 useErrorBoundary 속성 false로 수정
> [ 동현 ] 디펜던시 어레이 안채워진 것 수정(로그인, 회원가입, 비밀번호 변경페이지) ,로그인페이지 비동기부분 훅 분리

- src/components/organisms/Sidebar/SidebarChannels.tsx
close #223 
- 사이드바 스크롤 이벤트 버블링 현상 제거
> [ 혜수 ] 사이드바 스크롤 이벤트 버블링 현상 막기 완료

- src/components/organisms/Sidebar/Sidebar.styles.ts
- src/components/templates/PageTemplate/PageTemplate.tsx
close #232 
- div를 이용해 사이드바와 outlet 분리
> [ 혜수 ] 좁은 너비에서 사이드바 밖 부분 클릭시 사이드바 닫히는 기능 추가
